### PR TITLE
Improve eslint rules

### PR DESCRIPTION
**Pull request by henryjw**
Solves #181.

- Updated root eslint config
- Added new config that overrides root config for examples folder
- Updated code to implement the new rules
- Examples are not ommitted from the lint check in the `build` script (can easily be done)

### CODE REVIEW

**Comment by henryjw** [comment]
@joelnet BTW, you should consider squashing the commits when you merge. It helps keep the commit history a bit cleaner in `master`!

**Comment by joelnet** [comment]
Okay I have merged your changes in. I squashed the commits, it looks like squash doesn't keep the history of your changes, so github isn't reporting you as a contributor.

I'll have to make sure commits are squashed prior to a PR being submitted so this doesn't happen again.

Anyway, I added you to the list of contributors in the main README.

Thanks again for your contribution!

**Comment by henryjw** [comment]
Yea. I think it only keeps the author when the original PR is merged. But it's all good. Glad I was able to help.

**Comment by joelnet** [comment]
Plenty more issues to contribute to ;)

Also in desperate need of feedback from people writing applications with it.

**Pull request closed without merging**
