### PR TITLE
Fix Just.map should not perform any checks

### PR DESCRIPTION
**Pull request by thanhcng**
This fixex #251

### CODE REVIEW

**Comment by joelnet** [comment]
This looks pretty good. I think the code could be simplified on line 20 by just returning then value and eliminating the ternary below it.


```javascript
    return func(this.value)
```

**Comment by thanhcng** [comment]
> 
> 
> This looks pretty good. I think the code could be simplified on line 20 by just returning then value and eliminating the ternary below it.
> 
> ```js
>     return func(this.value)
> ```

If I do that, the some of the map tests will fail, because map would return a value instead of Just object. Then I'd have to fix those tests and anything that depends on map returning an object as well

**Comment by joelnet** [comment]
Ahh this was my bad. I had mislead you in the issue. `map` should always return a `Just`.

So the function should be:

```javascript
function map(func) {
  return Just(func(this.value))
}
```

and the test should be
```javascript
  test('when map returns undefined return undefined', () => {
    expect.assertions(1)
    const expected = Just(undefined)
    const actual = Just(666).map(() => undefined)
    expect(actual).toEqual(expected)
  })
```

That was my bad!

**Comment by joelnet** [comment]
I have merged your changes into develop. I had to rebase onto develop and github doesn't recognize this PR as merged.

**Pull request closed without merging**
