### PR TITLE
object category

### PR DESCRIPTION
**Pull request by luizbills**
new functions:

- `get :: String -> Any -> Object -> Any`
- `set :: String -> Any -> Object -> Any`
- `clone :: Object -> Object`
- `has :: String -> Object -> Boolean` (maybe)

### CODE REVIEW

**Comment by joelnet** [comment]
That's a good idea. Could you also include a couple unit tests. Also include a test for when `obj` is null so that it also returns null instead of throwing an exception.

We should also have a setter. Maybe `get` and `set` would be good names? `set` should also make a copy of the object and not mutate the original object.

**Comment by luizbills** [comment]
Also will be nice use `/` to acess object children:

```js
const state = {
  user: {
    name: {
      first: 'Luiz'
    }
  }
}

// example 1
const main = pipe([
  get ('user/name/first') ('unknown'),
  log
])
run ({ main, state }) // => Luiz

// example 2
const main = pipe([
  get ('user/name/last') ('unknown'),
  log
])
run ({ main, state }) // => unknown
```

**Comment by joelnet** [comment]
They aren't reserved words, but I am not 100% sure they won't be a problem. They'll just be functions that can be imported so you could import them as any name you wanted (if there was a conflict). Since MojiScript is so strict on what you can do, I think it would be fine to use `get` and `set`. also `path` (like ramda) would be fine too.

The problem with having a string that is split, is the delimiter. You lose the potential to use that delimiter in objects.

```javascript
const obj = {
  "my/prop": "success"
}
```

Check out Ramda's implementation of path: https://ramdajs.com/docs/#path. They solve this by accepting an array. That way the function doesn't have to perform a split and you don't have the banned delimiter problem.

**Comment by luizbills** [comment]
In my proposal I suggested escape (with backslash) this properties.

```js
const obj = {
  "my/prop": "success"
}

get ('my\\/prop') ('default') (obj) // => "success"
// or (with dot)
get ('my\.prop') ('default') (obj) // => "success" 
```

**Comment by luizbills** [comment]
is very uncommon the use of '/' or '.' in properties names

**Comment by luizbills** [comment]
> Check out Ramda's implementation of path

I think it's very ugly to use an array there

**Comment by luizbills** [comment]
You convinced me. but I think we can offer default values by default. This will reduce our API. If someone not need a default value, just call `get (arrayProps) ()`.

And will be weird have a function `get` and another `path`, would have to be `getPath` to be more consistent.

**Comment by luizbills** [comment]
But we have some logic helpers to take care of default values

```js
const ifNull = when ((x) => null == x)
const main = pipe([
  get ('name')
  ifNull ('default name'),
  log
])
```

**Comment by luizbills** [comment]
So... the current object API will be

- `get (keys) (obj)`
    - returns null if fails
- `set (key) (value) (obj)`

I vote for `get` accepts an array as first argument instead we implement `path`.

**Comment by joelnet** [comment]
We might still need a separate func for default values. Imagine this scenario:

```javascript
const obj = {
  a: null,
  b: 0,
  c: false
}

get ('a') ('n/a') (obj)
get ('b') ('n/a') (obj)
get ('c') ('n/a') (obj)
```

I want a to return `null`, b to return `0` and c to return `false`.

I think the default value should kick in if the prop doesn't exist.

```javascript
const obj = {
  a: null
}

get ('a') ('n/a') (obj) //=> null
get ('b') ('n/a') (obj) //=> 'n/a'
```

This is how Ramda's propOr works https://ramdajs.com/docs/#propOr

**Comment by luizbills** [comment]
as I mentioned before, I think the default values can be handled with logic helper:

```js
const ifNull = when ((x) => null == x)
const main = pipe([
  get ('name'), // returns null if fails
  ifNull ('default name'), // returns "default name" if is null
  log
])
```

default values in `get` is becoming very opinionated, it is unecessary complexity

**Comment by luizbills** [comment]
@joelnet I pushed 3 functions with tests:

- `get (prop) (obj)`
- `getPath (array) (obj)`
- `set (prop) (value) (obj)`

All tests passing

**Comment by joelnet** [comment]
I want to be able to handle these scenarios:

```javascript
const obj = { a: null, b: undefined }

test('prop doesn't exist', () => {
  const obj = { a: null }
  const actual = getOr ('unknown') ([ 'c' ]) (obj)
  expect(actual).toBe('unknown')
})

test('prop returns null', () => {
  const obj = { a: null }
  const actual = getOr ('unknown') ([ 'a' ]) (obj)
  expect(actual).toBe(null)
})

test('prop returns undefined', () => {
  const obj = { a: undefined }
  const actual = getOr ('unknown') ([ 'b' ]) (obj)
  expect(actual).toBe(undefined)
})
```

If `getOr` is created first, then `get` would just be this one liner:

```javascript
const get = getOr (null)
```

**Comment by joelnet** [comment]
I think this would be a good case to use an `Either` or `Maybe`. Sanctuary and Ramda both solve this different ways.

Returning something like `Just (null)` vs `Nothing` would be perfect but at this point, I'd like to keep the library free of dependencies. Though those types may be added in the future.

**Comment by joelnet** [comment]
We should also split up `clone` into `clone` and `deepClone`.

Also set shouldn't perform a `deepClone`.

So something like this should be valid:

```
test('set shallow clones', () => {
  const z = { z1: 'zzz' }
  const obj = { a: 1, z }
  const newObj = set ('a') (2) (obj)
  z.z1 = 'abc'
  expect(newObj.z.z1).toBe('abc')
})
```

**Comment by joelnet** [comment]
It would also be good symmetry to provide a `setPath` function. If there is a `get` and `getPath`, it makes sense to have a `set` and `setPath`. `setPath` should also shallow clone, but recursively so the multiple paths are cloned, but the other branches are untouched.

**Comment by joelnet** [comment]
`clone` should also be able to clone objects that contain an `Array`.

```javascript
  test('can clone arrays', () => {
    const obj = {
      list: [1, 2, 3]
    }
    const actual = clone(obj).list
    expect(is(Array)(actual)).toBe(true)
  })
```

**Comment by luizbills** [comment]
> We should also split up clone into clone and deepClone.

`get` and `set` became get, getOr, getPath, set, setPath, clone, deepClone... :rofl:
It is hard to keep mojiscript small

> It would also be good symmetry to provide a setPath function

Yes, it is make sense to have `setPath`, but I will need your help.

**Comment by joelnet** [comment]
> get and set became get, getOr, getPath, set, setPath, clone, deepClone... 🤣
It is hard to keep mojiscript small

I anticipated this. which is why I didn't add them yet. haha

You start small, but then open up a rabbit hole.

**Comment by luizbills** [comment]
I'm almost closing that issue haha

**Comment by joelnet** [comment]
haha!

I have also been converting a lot of code I am writing to use a similar pattern: https://github.com/reduxjs/reselect.

So you would create selectors to get your values like:

```javascript
// so instead of doing
const getName = get ('name')

// you just do
const getName = obj => obj.name

// or
const getName = ({ name }) => name
```

Then you just use your created function.

The lib only selects though. No set.

**Comment by luizbills** [comment]
I'll close this PR for awhile. But I will not delete this branch.

**Comment by joelnet** [comment]
If this one is on pause, you could create example projects for how to do this with `Ramda` and `Sanctuary`.

**Comment by luizbills** [comment]
I was wanting to create some examples with UI/frontend. I'll think of something

**Comment by joelnet** [comment]
If you need help, let me know.

**Comment by joelnet** [comment]
I think this is still a good idea. Let's start small though, one func at a time so we don't bite off too much at one time. I think the `clone` is a good start.

**Pull request closed without merging**
